# These are supported funding model platforms

github: [webkmsyed] # Replace with your GitHub username(s)
patreon: # Replace with your Patreon username
open_collective: # Replace with your Open Collective project name
ko_fi: # Replace with your Ko-fi username
tidelift: # Replace with your Tidelift platform and package name, e.g., "npm/babel"
community_bridge: # Replace with your Community Bridge project name
liberapay: # Replace with your Liberapay username
issuehunt: # Replace with your IssueHunt project name
lfx_crowdfunding: # Replace with your LFX Crowdfunding project name
polar: # Replace with your Polar username
buy_me_a_coffee: [webkmsyed] # Replace with your Buy Me a Coffee username
custom: ["https://jargoniseasy.com"] # Replace with up to 4 custom sponsorship URLs
